name: anonia
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.5
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.5
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^9.2.0
  get: ^4.6.1
  google_sign_in: ^5.2.1
  html: ^0.15.0
  provider: ^6.0.1
  settings_ui: ^2.0.1
  responsive_framework: ^0.1.7
  chat_bubbles: ^1.2.0
  jiffy: ^5.0.0
  intl: ^0.17.0
  emoji_picker_flutter: ^1.1.2

flutter_native_splash:
  color: "#ffffff"

  image: assets/people.png

  android: true

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/favicon/favicon.png"



flutter:
  uses-material-design: true

  assets:
    - assets/
