// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtNc7g9KG9pScc4cy1CQ6FnruTjyOAvds',
    appId: '1:45132570652:web:42ddc37e584c08cb63bfd9',
    messagingSenderId: '45132570652',
    projectId: 'anonia-project',
    authDomain: 'anonia-project.firebaseapp.com',
    storageBucket: 'anonia-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt8BnqzAgdsorrZqHWbInE7La9ChHc6A8',
    appId: '1:45132570652:android:dd28533b18d98a7163bfd9',
    messagingSenderId: '45132570652',
    projectId: 'anonia-project',
    storageBucket: 'anonia-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLmPbfShc6YIBuYZ6fsjqo5QcdhaBFIwM',
    appId: '1:45132570652:ios:5d36d5bcffe8f27e63bfd9',
    messagingSenderId: '45132570652',
    projectId: 'anonia-project',
    storageBucket: 'anonia-project.appspot.com',
    iosClientId: '45132570652-hleu952nd6nvlgmf2c36909gq2vaf4fa.apps.googleusercontent.com',
    iosBundleId: 'com.anonia.app',
  );
}
